### ISSUE TITLE
segy.open error:could not parse geometry, open with strict=False

### ISSUE THREAD

**Issue by maihao14** [Statoil/segyio#264] opened 2018-07-07 08:04 UTC
I try to open a poststack segy file but it failed. And I do not know how to deal with it.
HERE IS THE CODE:  I will be very appriciate for your reply!
```
    file = 'D:\MaiHao\DATA\DFB_DATA\ys250-300.sgy'
    with segyio.open(file, "r+") as segyfile:

    # Memory map file for faster reading (especially if file is big...)
        segyfile.mmap()

    # Print binary header info
        print(segyfile.bin)
        print(segyfile.bin[segyio.BinField.Traces])

    # Read headerword inline for trace 10
        print(segyfile.header[10][segyio.TraceField.INLINE_3D])

    # Print inline and crossline axis
        print(segyfile.xlines)
        print(segyfile.ilines)
```

**Comment by jokva** [comment] 2018-07-07 08:12
We'll need to know a little bit more about your file, because segyio is unable to figure out your volume.

Pass `ignore_geometry = True` or `strict = False` to `open`. That way, only direct trace access will work, but at least the file opens.

Then, do `f.attributes(segyio.TraceField.INLINE_3D)[:]` and print the resulting array. It should give us a good idea of what's going on.

**Comment by maihao14** [comment] 2018-07-07 08:47
I try to add `ignore_geometry = True `or ` strict = False ` but the error message still the same
And in OS X  it does not go to this situation.    
By the way  could you tell me how to duplicate the data out and display the data?   
I try to use :  ' data = f.trace '  or 'data = np.copy(f.data[:])'  it not seems to work .   
and  nothing come to spyder data inspector

**Comment by jokva** [comment] 2018-07-07 09:01
You can open the file on OS X, but not on Windows? How large is it?

The easiest way to obtain a copy of all of the data is to do `data = f.trace.raw[:]`, or use the `cube` function in `segyio.tools`. By  default, segyio reads lazily from the file, and re-uses buffers for speed, to allow files much larger than memory, but that means things won't copy unless you explicitly ask it to.

For what it's worth, `data = np.concatenate([np.copy(x) for x in f.trace])` would've worked, so you were pretty close. Every individual trace must be copied.

**Comment by maihao14** [comment] 2018-07-07 09:49
Thanks a lot .  I have copied the data successfully .  
Here is one more question,  I use segyviewer try to plot the data , but it imported error:  
ImportError: 
    Importing PyQt4 disabled by IPython, which has
    already imported an Incompatible QT Binding: pyqt5 . 
So I wanna know is it still available  ?  Or do you recommend some tools to plot seismic data directly in data metrics  format(numpy, not sgy-file)

**Comment by jokva** [comment] 2018-07-07 09:56
If you're already in ipython (or a jupyter notebook or similar), I'd recommend just plotting it directly from there.

**Comment by jokva** [comment] 2018-07-10 06:42
Is it so that you can successfully open the file on OS X, but the same file fails to open on Windows?

**Comment by maihao14** [comment] 2018-07-11 00:02
I try again to add  `strict = False `  in Windows code  the error fixed.
The data could rise this problem is a man-hand-made slice from a whole prestack volume.

**Comment by jokva** [comment] 2018-07-11 06:49
Did the same file open *without* `strict = False` on OS X? Because there shouldn't be a difference between Windows and OS X in that regard, but you never know with bugs.

It wouldn't happen to use non-standard header fields for inline/crossline numbers, would it?

**Comment by Shubham281993** [comment] 2018-08-04 09:25
Hi,
I am trying to open a segy file from S3, is there any way that I can do that by using SegyIo library?

**Comment by jokva** [comment] 2018-08-04 09:27
segyio relies on local file access, so if you can download the file to the node in question then sure. There is no support for fetching from buckets in segyio itself.

**Comment by Shubham281993** [comment] 2018-08-04 09:29
What if the file size is very much in TB's?

**Comment by jokva** [comment] 2018-08-04 09:33
That's problematic. The problem is segyio relies on `fopen`, and there is no S3-compatible `fstream` library available as far as I'm aware. I struggle to find good documentation on how to access S3 files as if they were local transparently. If you know of any resoures, I'd love to see them.

**Comment by Bomb281993** [comment] 2018-08-04 09:42
Can Boto3 library be used for this?

**Comment by jokva** [comment] 2018-08-04 09:50
Maybe, but all examples I've found boil down to first downloading the file, and then accessing it locally.

**Comment by jokva** [comment] 2018-08-06 10:03
@Bomb281993 Try setting up a FUSE for S3, and use segyio with that.

https://github.com/s3fs-fuse/s3fs-fuse

**Comment by Bomb281993** [comment] 2018-08-09 11:43
@jokva , I have a custom seg-y which is having custom byte definition for  trace-header.
Can we customize the segyio library for reading these custom byte definition from the segy file

**Comment by jokva** [comment] 2018-08-10 07:41
What do you "custom trace header"? Is it just byte offset of key information geometric (inline/crossline numbers), or is it something else than 240 bytes long?

Arguably it's not really SEG-Y either way, but if it's the latter segyio itself needs to be modified.

**Comment by Bomb281993** [comment] 2018-08-10 10:58
Custom trace header  means within that 240 bytes , attributes having new byte definition like 1-8,9-15 like that.

**Comment by jokva** [comment] 2018-08-10 11:00
That's pretty wonky, but as long as the boundaries are the same as in the standard, segyio shouldn't choke.

Some will surely have to be read in multiple operations, and then combined manually, but it's surely doable.

**Comment by jokva** [comment] 2018-08-10 15:25
It's governed by a switch in the C core. If you need this feature, I suggest you for now manually unpack headers with `f.header.buf`. Maybe it will be a support feature one day.

**Comment by Bomb281993** [comment] 2018-08-10 15:34
I am sorry jokva i couldn't get that, can you please shed some more light on that ,so that it will be easy for me to change that.

**Comment by jokva** [comment] 2018-08-10 15:44
If you access your headers with `f.header[n]`, that object has a `.buf` field. That field is internal (and unlikely to change), so using it directly is not supported.

However, it's a regular byte array. You can ready your data from that with the regular bytes interface, so `buf[0:8]`, `buf[8:16]` etc., and read the bytes as ints.

**Comment by Bomb281993** [comment] 2018-08-10 15:50
Ok so buf[0:8],buf[8:16] refers to the byte info of the headers and the datatypes will be int.

**Comment by jokva** [comment] 2018-08-10 21:30
Almost.

`int.from_bytes(buf[0:8], byteorder='big', signed = True)`

**Comment by Bomb281993** [comment] 2018-08-11 10:31
I am using 
a=f.header[1].buf[0:4]
struct.unpack("L", a)
but it is not giving correct value.
Is this correct as I am using Python 2.7.

**Comment by Bomb281993** [comment] 2018-08-11 10:31
I am using 
a=f.header[1].buf[0:4]
struct.unpack("L", a)
but it is not giving correct value.
Is this correct as I am using Python 2.7.

**Comment by jokva** [comment] 2018-08-11 12:43
Depends. Are the fields written in little- or big-endian?

**Comment by jokva** [comment] 2018-11-06 08:49
Since we haven't heard anything in a while, I'm closing this issue. Please re-open or create a new issue if this did not solve your problem.

**Closed by jokva** 2018-11-06 08:49 UTC
